project:
  type: r3-theme
  # pre-render: bash _build-slides.sh
  # resources:
  #   - slides/*.html

book:
  title: Git for Collaborative Teams
  subtitle: "An introductory course on team-based collaboration with Git and GitHub"
  body-header: |
    ::: {.callout-warning appearance="default" icon="true"}
    ðŸš§ This course is still in active development ðŸš§
    :::
  author: 
    - name: Luke W. Johnston
      orcid: 0000-0003-4169-2616
    - name: Signe Kirk BrÃ¸dbÃ¦k
  date: last-modified
  site-url: https://git4cats.rostools.org
  repo-url: https://github.com/rostools/git4cats
  chapters:
    - index.qmd
    - part: "Preamble"
      chapters:
      - preamble/syllabus.qmd
      - preamble/schedule.qmd
      - preamble/pre-course.qmd
    - part: "Sessions"
      chapters:
      - sessions/introduction.qmd
      - sessions/lesson.qmd
      - sessions/what-next.qmd
  appendices:
    - appendix/social.qmd
    - appendix/for-instructors.qmd
    - appendix/references.qmd
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.html
      - text: "Code of Conduct"
        href: "https://guides.rostools.org/conduct.html"

format:
  r3-theme-html: default

editor:
  markdown:
    wrap: 72
    canonical: true

execute:
  eval: false
